apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: altrupets-app-tls
  namespace: altrupets-dev
spec:
  secretName: altrupets-app-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.altrupets.app"
