apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  NODE_ENV: "development"
  PORT: "3001"
  DB_HOST: "postgres-dev-service.altrupets-dev.svc.cluster.local"
  DB_PORT: "5432"
  AVATAR_STORAGE_TYPE: "local"
  S3_ENDPOINT: ""
  S3_BUCKET_NAME: ""
