apiVersion: v1
kind: Service
metadata:
  name: web-superusers-service
  labels:
    app: web-superusers
spec:
  type: ClusterIP
  selector:
    app: web-superusers
  ports:
    - name: http
      port: 3002
      targetPort: http
