apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-b2g
spec:
  template:
    metadata:
      annotations:
        build.id: dev
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
