name: altrupets
description: "Aplicaci√≥n Flutter con Clean Architecture y Riverpod para el proyecto Altrupets."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management - Riverpod
  flutter_riverpod: ^2.5.1

  # Immutability & Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Functional Programming
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Networking
  dio: ^5.4.0
  http: ^1.2.0
  
  # GraphQL
  graphql: ^5.1.2
  graphql_flutter: ^5.1.2

  # Local Storage
  shared_preferences: ^2.2.2

  # Network Check
  internet_connection_checker: ^1.0.0+1

  # Utilities
  intl: ^0.20.2

  # Theming
  google_fonts: ^6.1.0

  # Geolocalization
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # Image Picker
  image_picker: ^1.1.2

  # Secure Storage
  flutter_secure_storage: ^9.2.2
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # Internationalization
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/style_dictionary/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Lemon Milk
      fonts:
        - asset: assets/fonts/lemon_milk/LemonMilkLight-owxMq.otf
          weight: 300
        - asset: assets/fonts/lemon_milk/LemonMilkLightItalic-7BjPE.otf
          weight: 300
          style: italic
        - asset: assets/fonts/lemon_milk/LemonMilkRegular-X3XE2.otf
          weight: 400
        - asset: assets/fonts/lemon_milk/LemonMilkRegularItalic-L3AEy.otf
          weight: 400
          style: italic
        - asset: assets/fonts/lemon_milk/LemonMilkMedium-mLZYV.otf
          weight: 500
        - asset: assets/fonts/lemon_milk/LemonMilkMediumItalic-d95nl.otf
          weight: 500
          style: italic
        - asset: assets/fonts/lemon_milk/LemonMilkBold-gx2B3.otf
          weight: 700
        - asset: assets/fonts/lemon_milk/LemonMilkBoldItalic-PKZ3P.otf
          weight: 700
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
