apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
  - ../../base

namePrefix: qa-

commonLabels:
  environment: qa
  app.kubernetes.io/version: "1.0.0-qa"

commonAnnotations:
  environment: qa
  deployedBy: "kustomize"

patches:
  - path: patches/gateway-patch.yaml
    target:
      kind: Gateway
      name: default-gateway

configMapGenerator:
  - name: gateway-config
    behavior: replace
    literals:
      - environment=qa
      - logLevel=info

replicas:
  - name: gateway-controller
    count: 2

images:
  - name: gateway-controller
    newName: nginx/nginx-ingress
    newTag: "qa-stable"
