apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: altrupets-apps
  namespace: argocd
spec:
  project: altrupets-dev
  source:
    repoURL: https://github.com/your-org/altrupets-monorepo.git
    targetRevision: main
    path: k8s/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
