# Base HTTPRoutes - These will be patched per environment
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default-route
spec:
  parentRefs:
    - name: default-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: default-backend
          port: 80
