apiVersion: v1
kind: Service
metadata:
  name: web-b2g-service
  labels:
    app: web-b2g
spec:
  type: ClusterIP
  selector:
    app: web-b2g
  ports:
    - name: http
      port: 3003
      targetPort: http
